### ISSUE TITLE
Security Roadblock - Please allow for the relocation of the msmdsrv.exe file as it violates McAfee rules

### ISSUE THREAD

**Issue by scottstauffer-fc** [action-bi-toolkit/pbi-tools#60]
REQUEST: 
Can the location of msmdsrv.exe be customizable or placed in the same directory as the pbi-tools folder for execution instead of the User's Profile tree?  

On execution I get an exception: 

C:\Source\action-bi-toolkit>pbi-tools.exe extract "PowerBITestReport.pbix"
Using Power BI Desktop install: 2.100.785.0 (21.12) at C:\Program Files\WindowsApps\Microsoft.MicrosoftPowerBIDesktop_2.100.785.0_x64__8wekyb3d8bbwe\bin
MSMDSRV.EXE found at C:\Program Files\WindowsApps\Microsoft.MicrosoftPowerBIDesktop_2.100.785.0_x64__8wekyb3d8bbwe\bin\msmdsrv.exe
Working directory: C:\Users\scott.stauffer\AppData\Local\Temp\tmpDED5.tmp
Shadow-copying msmdsrv...
Could not terminate msmdsrv.exe.
System.InvalidOperationException: No process is associated with this object.
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.get_HasExited()
   at PbiTools.PowerBI.AnalysisServicesServer.Dispose() in X:\action-bi-toolkit\pbi-tools\pbi-tools-cli\src\PBI-Tools\PowerBI\AnalysisServicesServer.cs:line 178
An unhandled exception occurred.
System.UnauthorizedAccessException: Access to the path 'C:\Users\scott.stauffer\AppData\Local\pbi-tools\Microsoft.MicrosoftPowerBIDesktop_2.100.785.0_x64__8wekyb3d8bbwe\msmdsrv.exe' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at PbiTools.Utils.DependenciesResolver.ShadowCopyMsmdsrv(String path) in X:\action-bi-toolkit\pbi-tools\pbi-tools-cli\src\PBI-Tools\Utils\DependenciesResolver.cs:line 183
   at PbiTools.PowerBI.AnalysisServicesServer.<Start>b__21_3(Exception ex, Int32 i) in X:\action-bi-toolkit\pbi-tools\pbi-tools-cli\src\PBI-Tools\PowerBI\AnalysisServicesServer.cs:line 117
   at Polly.RetrySyntax.<>c__DisplayClass5_0.<Retry>b__0(Exception outcome, TimeSpan timespan, Int32 i, Context ctx) in /_/src/Polly/Retry/RetrySyntax.cs:line 91
   at Polly.Retry.RetryPolicy.<Implementation>b__5_0[TResult](DelegateResult`1 outcome, TimeSpan timespan, Int32 retryCount, Context ctx) in /_/src/Polly/Retry/RetryPolicy.cs:line 41
   at Polly.Retry.RetryEngine.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Action`4 onRetry, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider) in /_/src/Polly/Retry/RetryEngine.cs:line 76
   at Polly.Retry.RetryPolicy.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken) in /_/src/Polly/Retry/RetryPolicy.cs:line 35
   at Polly.Policy.Execute[TResult](Func`3 action, Context context, CancellationToken cancellationToken) in /_/src/Polly/Policy.ExecuteOverloads.cs:line 164
   at PbiTools.PowerBI.AnalysisServicesServer.Start() in X:\action-bi-toolkit\pbi-tools\pbi-tools-cli\src\PBI-Tools\PowerBI\AnalysisServicesServer.cs:line 123
   at PbiTools.PowerBI.DataModelConverter.LaunchTabularServerAndExecuteCallback[T](Func`2 callback) in X:\action-bi-toolkit\pbi-tools\pbi-tools-cli\src\PBI-Tools\PowerBI\DataModelConverter.cs:line 79
   at PbiTools.Model.PbixModel.FromReader(PbixReader reader, String targetFolder, Nullable`1 portNumber) in X:\action-bi-toolkit\pbi-tools\pbi-tools-cli\src\PBI-Tools\Model\PbixModel.cs:line 154
   at PbiTools.CmdLineActions.Extract(String pbixPath, Int32 pbiPort, String extractFolder, ExtractActionCompatibilityMode mode, ModelSerializationMode modelSerialization, MashupSerializationMode mashupSerialization) in X:\action-bi-toolkit\pbi-tools\pbi-tools-cli\src\PBI-Tools\CmdLineActions.cs:line 96
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at PowerArgs.ArgAction.Invoke()
   at PbiTools.Program.Main(String[] args) in X:\action-bi-toolkit\pbi-tools\pbi-tools-cli\src\PBI-Tools\Program.cs:line 76

I looked in:
C:\ProgramData\McAfee\Endpoint Security\Logs\AccessProtection_Activity.log

and found:

2021-12-29 18:51:15.696Z |Activity|ApBl |mfeesp | 7424| 2872|AP |XModuleEvents.cpp(851) | scott.stauffer ran C:\Source\action-bi-toolkit\pbi-tools.exe, which tried to access the file C:\Users\scott.stauffer\AppData\Local\pbi-tools\Microsoft.MicrosoftPowerBIDesktop_2.100.785.0_x64__8wekyb3d8bbwe\msmdsrv.exe, violating the rule "Block EXE from running in a User's profile", and was blocked. For information about how to respond to this event, see KB85494.

**Comment by mthierba** [comment]
Thanks for reporting this @scottstauffer-fc 

There are two possible root causes for the issue:
- COPYing the exe into the *Users* folder is blocked
- EXECUTing the exe from that location is prohibited

Judging from the error log, I believe it's the 1st issue. However, before investing too much effort into a fix which might turn out not to be sufficient, let's test this with a private patch first.
I'll make a change allowing to specify a custom file location and let you test that one on your side (I can't reproduce the issue on my end).

If the fix works, a new environment setting `PBITOOLS_ShadowCopyDir` will be available allowing to override the default location in the *Users* folder.

**Comment by scottstauffer-fc** [comment]
would the be anything that requires running as a local administrator?
We are also hitting walls with with AV temporarily turned off.

**Comment by mthierba** [comment]
> would the be anything that requires running as a local administrator?
> We are also hitting walls with with AV temporarily turned off.
> 

Don't anticipate a need to run this in an elevated shell (as admin). The tool is meant to be used as a companion to Power BI Desktop, which also works for non-admin users.

**Comment by scottstauffer-fc** [comment]
I ran the tool and it failed and an admin logged in and remotely connected to elevate my command line window and it worked.  I will explore more on my personal equipment this coming weekend.

**Comment by scottstauffer-fc** [comment]
https://twitter.com/SQLSocialite/status/1476781514113224707
Opening the question to a wider audience - Twitter
"Is there a tool to see when admin creds are needed to successfully execute code? Maybe something in #sysinternals suite? Executing code and AV has been ruled out; now it seems elevated command prompt is needed, but wondering what can change to allow it to work without admin creds"

**Comment by mthierba** [comment]
@scottstauffer-fc Please retry with the patch version available here: https://github.com/action-bi-toolkit/pbi-tools/releases/tag/1.0.0-beta.7%2B60.1

Set the `PBITOOLS_AppDataDir` environment var to a folder your user has full access to prior to running `pbi-tools extract`.

**Comment by scottstauffer-fc** [comment]
Success!

USER Environmental variables are set in Windows 10 by going to 

1. "Setting" and typing "env" in search bar and select "Edit environmental variables for your account"; 
2. Click the "New..." button in the top section "User variables for"
3. This is what I added:
> ```
> Variable name:     PBITOOLS_AppDataDir
> Variable value:    C:\Source\action-bi-toolkit\AppDataDir
> ```

**Comment by mthierba** [comment]
@scottstauffer-fc This is now available in the latest release (Beta.8): https://github.com/pbi-tools/pbi-tools/releases/tag/1.0.0-beta.8
